### ISSUE TITLE
Solution: Cannot read property 'Deferred' of undefined

### ISSUE THREAD

**Issue by nucleartide** [thejameskyle/marionette-wires#56]
This isn't really an issue, I just want to leave a comment about how to fix the jQuery undefined issue.

So if you `npm install backbone` and `npm install backbone.marionette`, you will get the latest versions of Backbone and Marionette (which, as of this writing, is 1.2.0 for Backbone and 2.4.1 for Marionette). Marionette 2.4.1 needs a version of Backbone that is between 1.0.0 and 1.1.2. Thus, when you require Backbone and jQuery, and set jQuery on the Backbone object, that Backbone object (which is v1.2.0) won't be the same as the Backbone `require()`'d by Marionette (which is v1.0.0 to v1.1.2). The solution to this is to specify an exact version of 1.1.2 for Backbone in your `package.json`.

More details here: https://github.com/marionettejs/backbone.marionette/issues/2559

Alerting the commenters in that issue: @wss-world, @marcsky

**Comment by MJBNetDev** [comment]
I had the same error in a project I was creating. However I found that by using the babelify version "babelify": "^5.0.3" instead of the latest fixed the problem for me.   If you just use the latest version in wires "babelify": "^6.1.2", it gives me the same error with everything else the same.    So for a quick fix you can try using the later verison of Babelify.   Sounds like I need to double check the versions of backbone also.
